Esercitazione 27/9/23
ittagnelli/5INFO_2324 pull request #10
Opened 2023-09-27 13:01 UTC by Luca-Porta

2023-09-27 13:02 UTC, Luca-Porta commented
Esercitazione 27/9/23

2023-09-28 11:39 UTC, profmancusoa requested changes
il formato è cognome_nome/RETI

aggiorna la PR

2023-09-28 15:37 UTC, Luca-Porta commented
PR aggiornata

2023-09-30 19:33 UTC, profmancusoa approved these changes

2023-09-30 19:33 UTC, merged