compito 27/09/23
ittagnelli/5INFO_2324 pull request #11
Opened 2023-09-27 13:18 UTC by gioele-mari

compito

2023-09-28 11:39 UTC, profmancusoa requested changes
il formato è cognome_nome/RETI

aggiorna la PR

2023-09-30 19:32 UTC, profmancusoa requested changes
PR ancora non accettabile

2023-10-02 10:51 UTC, gioele-mari commented
Ho fatto prof

2023-10-04 11:43 UTC, profmancusoa approved these changes

2023-10-04 11:43 UTC, merged